export const SACCO_CONFIG = {
  name: process.env.NEXT_PUBLIC_SACCO_NAME || "Wananchi Mali",
  shortName: process.env.NEXT_PUBLIC_SACCO_SHORT_NAME || "Wananchi Mali",
  tagline: process.env.NEXT_PUBLIC_SACCO_TAGLINE || "Empowerment through equity, inclusion, and governance",
  supportEmail: process.env.NEXT_PUBLIC_SACCO_SUPPORT_EMAIL || "support@wananchimali.com",
  logoUrl: process.env.NEXT_PUBLIC_SACCO_LOGO_URL || "/wananchiLogoNoBg.png",
  logoSmallUrl: process.env.NEXT_PUBLIC_SACCO_LOGO_SMALL_URL || "/wananchiLogoNoBg.png",
  primaryColor: process.env.NEXT_PUBLIC_SACCO_PRIMARY_COLOR || "#174271",
  accentColor: process.env.NEXT_PUBLIC_SACCO_ACCENT_COLOR || "#236c2e",
  primaryHoverColor: process.env.NEXT_PUBLIC_SACCO_PRIMARY_HOVER_COLOR || "#12345a",
  accentHoverColor: process.env.NEXT_PUBLIC_SACCO_ACCENT_HOVER_COLOR || "#1a5222",
  memberUrl: process.env.NEXT_PUBLIC_MEMBER_URL || "",
  adminUrl: process.env.NEXT_PUBLIC_ADMIN_URL || "",
  superuserUrl: process.env.NEXT_PUBLIC_SUPERUSER_URL || "",
};
